In [5]:
# doing this again
# but this time doing by dot multiplication of arrays and then putting it in dataframe(earlier we did dot product of dataframes)

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(0)
sales_amounts=np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [6]:
prices=np.array([10,8,12])
prices

array([10,  8, 12])

In [7]:
total_sales=prices.dot(sales_amounts.T)
total_sales


array([240, 138, 458, 232, 142])

In [8]:
total_sales.shape

(5,)

In [9]:
weekly_sales=pd.DataFrame(sales_amounts,index=["Mon","Tues","Wed","Thurs","Fri"],columns=["Almond butter","Peanut butter","Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [10]:
butter_prices=pd.DataFrame(prices,index=["Price"],columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

ValueError: Shape of passed values is (3, 1), indices imply (1, 3)

In [11]:
prices.shape

(3,)

In [12]:
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond butter","Peanut butter","Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [14]:
# Adding "Total($)" to the dataframe weekly_sales
# .tolist() is a method to put array to a dataframe as a column
# found on https://www.statology.org/add-numpy-array-to-pandas-dataframe/
weekly_sales["Total($)"]=total_sales.tolist()
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total($)
Mon               12             15              0       240
Tues               3              3              7       138
Wed                9             19             18       458
Thurs              4              6             12       232
Fri                1              6              7       142